# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc221d1829d133971c405088aae5d68723cd3f56d403a141452892702cec2041772a7c08b3203c3d22c37bdad75faff87aa0d480d404372438fe3f174e90800

test:
  secret_key_base: 258cdbbce25be17d0226a627be2673a5f19c5e12e6e9f7a702e4f26fc02e62b64c8e75d4719569a9b7c052933f2bf6bc30ef69573e4c34ad464e3afa86c40434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
